# TARGETS
# targets is a name for a operation.
# Ex:build, run is the target here.
# make + target-name - if only pass make it will build the first one.

build:
	g++ main.cpp -o main

build-object:
		g++ main.cpp -c main.o
		g++ main.o -o main

run:
		./main

clean:
	rm -f main
	rm -f *.o